name: app
publish_to: none
dependencies:
  angular: ^4.0.0
  angular_forms: 1.0.0
  angular_router: ^1.0.0
  electron: ^0.0.3
dev_dependencies:
  build_runner: ^0.6.1
  build_web_compilers: ^0.1.1
  html: ^0.13.0
dependency_overrides:
  build: ^0.11.0
  build_config: ^0.2.1
  built_collection: ^2.0.0
  build_test: ^0.9.4
  code_builder: ">=1.0.0 <3.0.0"
transformers:
  - app # Modifies index.html to point to main.dart.js
  - angular:
      entry_points:
        - web/main.dart